### ISSUE TITLE
Merge ag_proposal ?

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-doc#26]
@agouby on fait de ta branche "ag_proposal" le nouveau main ?
Il faut qu'on puisse valider dans la doc les discussions que l'on a sur "dodo" 🤣

**Comment by wardru** [comment]
Avant de merge dans main j'aimerais completer la partie MQTT, et egalement etre sur qu'on soit d'accord sur tous les points.\
Je m'occupe de la partie MQTT, et ensuite je ferai une MR avec approval obligatoire de toi et Bryan
