### ISSUE TITLE
Iterate on network.json

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-doc#52]
After some work on it, I think the spec must be improved 

Rename network.json -> connection.json

This file is important for the platform because it defines the parameters of the platform connection. Without this connection the platform is useless.

So the user must explicitly know if the connection is not configured as requested.

At platform boot, if:
 the file
 json object inside the file
 json fields
are badly formated. 

Then the platform must stop immediately and report an accurate error to the admin through the log file.

If the file is well formatted but some json field are missing, the platform must provide a default value for missing fields.

If the file does not exist, the platform has to start with the default connection parameters.

**Comment by XdoctorwhoZ** [comment]
Append also a section credentials (user, pass, cert) and a section host (name, port)

**Comment by wardru** [comment]
I agree with everything except a little detail.

If the file is not present, I would notify the user about and use default settings like you say @XdoctorwhoZ.
But if the file is well formatted and some fields are missing, I would suggest that we define some mandatory fields.

To me if the user creates the file, fills an IP but doesn't fill a port, he might be confused. Half written configs are usally bad configs.

For settings and devices that are more subject to evolution (adding devices later with a hunt etc) I agree, these are optional fields.

But connection fields are super important and describe the essence of the relationship between a platform and a broker. To avoid any support / bugs / confusion for the user, I would prefer that he explicitely sets these fields.

What do you think?

**Comment by wardru** [comment]
I would even prompt the user if the file is missing.

Because what if I had a connection.json file in /etc/panduza that connects to a specific broker, but I deleted the file by mistake.

The platform will launch thinking it should use default settings, but that's not what I wanted at all.

Maybe a prompt that says: "No configuration file found. Do you want to create one with default settings?"
